# OCR-Native LLM Configuration
# Revolutionary approach: All weights and data stored in OCR format

model:
  # Architecture
  d_model: 512
  n_layers: 12
  n_heads: 8
  d_ff: 2048
  vocab_size: 50000
  max_seq_length: 8192  # Much longer due to OCR efficiency
  
  # OCR-specific settings
  ocr_image_width: 1024
  ocr_image_height: 1024
  ocr_font_size: 14
  ocr_precision: 8
  ocr_compression_ratio: 0.7
  
  # Memory and context
  memory_window_size: 50000  # Much larger than traditional models
  ocr_memory_bank_size: 1000
  context_retention: 0.95

training:
  # Basic training
  learning_rate: 1e-4
  batch_size: 8
  gradient_accumulation_steps: 4
  num_epochs: 10
  
  # OCR-specific training
  ocr_loss_weight: 0.3
  text_loss_weight: 0.7
  ocr_pattern_learning_rate: 1e-5
  
  # Memory training
  memory_learning_rate: 1e-4
  memory_update_frequency: 100  # steps
  
  # Progressive training stages
  progressive_stages:
    stage_1:
      d_model: 256
      n_layers: 4
      seq_len: 2048
      batch_size: 16
      epochs: 2
    stage_2:
      d_model: 512
      n_layers: 8
      seq_len: 4096
      batch_size: 8
      epochs: 3
    stage_3:
      d_model: 768
      n_layers: 12
      seq_len: 8192
      batch_size: 4
      epochs: 5

ocr_processing:
  # Text to OCR
  text_to_ocr_enabled: true
  text_preprocessing:
    convert_to_uppercase: true
    replace_problematic_chars: true
    double_spaces: true
    add_punctuation_spacing: true
  
  # Speech to OCR
  speech_to_ocr_enabled: true
  speech_preprocessing:
    sample_rate: 16000
    normalize_audio: true
    add_silence_padding: true
  
  # Image to OCR
  image_ocr_enabled: true
  image_preprocessing:
    convert_to_grayscale: true
    enhance_contrast: true
    apply_threshold: true
    threshold_value: 128

memory_system:
  # OCR Memory Bank
  memory_bank_size: 1000
  memory_retrieval_top_k: 5
  memory_similarity_threshold: 0.85
  
  # Conversation Memory
  max_conversation_length: 50000
  memory_compression: true
  memory_compression_ratio: 0.8
  
  # Memory types
  memory_types:
    - "conversation"
    - "knowledge"
    - "weights"
    - "patterns"
    - "context"

attention:
  # OCR-optimized attention
  ocr_pattern_bias: true
  pattern_window_size: 11  # 5 before + 1 current + 5 after
  ocr_similarity_threshold: 0.7
  
  # Attention mechanisms
  use_ocr_context: true
  ocr_memory_integration: true
  pattern_recognition_layers: 4

output:
  # Text generation
  text_generation:
    max_length: 512
    temperature: 0.8
    top_p: 0.9
    top_k: 50
  
  # OCR output
  ocr_output:
    generate_ocr_images: true
    ocr_image_format: "PNG"
    ocr_compression: true
  
  # Response types
  response_types:
    - "text"
    - "ocr_image"
    - "mixed"

performance:
  # Optimization
  use_gradient_checkpointing: true
  use_mixed_precision: true
  gradient_clip_norm: 1.0
  
  # Memory optimization
  memory_efficient_attention: true
  ocr_memory_compression: true
  
  # Inference
  inference_batch_size: 1
  max_inference_length: 8192

evaluation:
  # Metrics
  metrics:
    - "perplexity"
    - "ocr_accuracy"
    - "memory_retrieval_accuracy"
    - "response_quality"
    - "conversation_coherence"
  
  # OCR-specific metrics
  ocr_metrics:
    - "text_to_ocr_accuracy"
    - "ocr_to_text_accuracy"
    - "pattern_recognition_accuracy"
    - "memory_ocr_consistency"
  
  # Evaluation frequency
  eval_frequency: 100  # steps
  save_frequency: 500  # steps

debugging:
  # Logging
  log_level: "INFO"
  log_ocr_processing: true
  log_memory_operations: true
  log_attention_patterns: true
  
  # Visualization
  save_ocr_images: true
  save_attention_weights: true
  save_memory_retrieval: true
  
  # Debug paths
  debug_output_dir: "./debug_output"
  ocr_images_dir: "./debug_output/ocr_images"
  attention_weights_dir: "./debug_output/attention_weights"

file_paths:
  # Data
  training_data: "./data/ocr_training_data.json"
  validation_data: "./data/ocr_validation_data.json"
  
  # Models
  model_save_dir: "./ocr_native_checkpoints"
  ocr_weights_dir: "./ocr_native_checkpoints/ocr_weights"
  
  # Logs
  log_dir: "./logs"
  tensorboard_dir: "./tensorboard_logs"
  
  # Output
  output_dir: "./output"
  generated_responses_dir: "./output/generated_responses"
  ocr_output_dir: "./output/ocr_output"

# OCR-specific optimizations
ocr_optimizations:
  # Font optimization
  font_family: "DejaVuSansMono"
  font_size_range: [12, 16]
  font_weight: "normal"
  
  # Image optimization
  image_contrast_enhancement: true
  image_noise_reduction: true
  image_sharpening: true
  
  # Text optimization
  text_character_spacing: 1.2
  text_line_spacing: 1.5
  text_margin: 20
  
  # Pattern recognition
  pattern_window_sizes: [5, 11, 21]
  pattern_similarity_thresholds: [0.6, 0.7, 0.8, 0.9]
  pattern_learning_rate_decay: 0.95