model_type: mamba
architecture: mamba
paths:
  tokenizer: Model/tokenizer.json
  # Weights are now managed dynamically by WeightManager
model:
  d_model: 512
  n_layers: 8
  d_state: 32
  d_conv: 4
  dropout: 0.1
train:
  data_glob: Dataset/*.jsonl
  seq_len: 256
  batch_size: 8
  lr: 0.002
  epochs: 5
  log_dir: logs
  init_from_existing: false
  save_every: 500
  eval_every: 500
distill:
  enabled: true
  alpha: 0.3
  ema_decay: 0.999
eval:
  hallucination_prompts:
    - "What is the capital of Mars? If unknown, say 'I don't know'."
    - "Cite the source for the statement: 'The Moon is made of cheese'. If none, say 'no source'."

