# Tantra OCR LLM Configuration
# Optimized for OCR language format, image processing, and enhanced memory

model:
  # Core architecture
  d_model: 1024
  n_layers: 24
  n_heads: 16
  d_ff: 4096
  dropout: 0.1
  
  # OCR-specific settings
  image_size: 512
  patch_size: 32
  num_patches: 256  # (512/32)^2
  ocr_precision: 8
  
  # Memory and weight storage
  memory_capacity: 10000
  weight_ocr_format: true
  memory_ocr_format: true
  
  # Multi-modal dimensions
  audio_dim: 256
  text_dim: 1024
  vision_dim: 1024
  
  # OCR processing
  ocr_confidence_threshold: 0.85
  weight_compression_ratio: 0.7
  memory_retention_epochs: 10

# Training configuration
training:
  # Progressive training stages
  stages:
    - stage: 1
      d_model: 256
      n_layers: 6
      memory_capacity: 100
      batch_size: 8
      lr: 0.001
      epochs: 5
      seq_len: 128
    - stage: 2
      d_model: 512
      n_layers: 12
      memory_capacity: 500
      batch_size: 4
      lr: 0.0005
      epochs: 7
      seq_len: 256
    - stage: 3
      d_model: 768
      n_layers: 18
      memory_capacity: 2000
      batch_size: 2
      lr: 0.0002
      epochs: 10
      seq_len: 512
    - stage: 4
      d_model: 1024
      n_layers: 24
      memory_capacity: 10000
      batch_size: 1
      lr: 0.0001
      epochs: 15
      seq_len: 1024
  
  # OCR-specific training
  ocr_training:
    enabled: true
    ocr_loss_weight: 0.1
    memory_loss_weight: 0.05
    pattern_recognition_weight: 0.2
    
  # Memory training
  memory_training:
    enabled: true
    memory_update_frequency: 10  # Update memory every N steps
    memory_retention_epochs: 10   # Keep memories for N epochs
    memory_diversity_weight: 0.1
    
  # Weight OCR storage
  weight_ocr_storage:
    enabled: true
    storage_frequency: 100  # Store weights as OCR every N steps
    compression_ratio: 0.7
    precision_digits: 8

# OCR processing configuration
ocr_processing:
  # Image settings
  image:
    width: 1024
    height: 1024
    channels: 3
    format: "RGB"
    
  # Text encoding settings
  text:
    precision_digits: 8
    encoding_scheme: "scientific"  # scientific, decimal, hex, binary
    max_values_per_image: 2000
    font_size: 10
    text_color: "black"
    background_color: "white"
    
  # OCR model settings
  ocr_model:
    primary: "pytesseract"
    fallback: "opencv"
    confidence_threshold: 0.85
    preprocessing:
      resize: true
      denoise: true
      contrast_enhancement: true
      binarization: true
      grayscale: true

# Memory bank configuration
memory_bank:
  # Memory storage
  storage:
    capacity: 10000
    similarity_threshold: 0.8
    max_memory_images: 1000
    cache_size: 100
    cleanup_frequency: 50  # Cleanup every N operations
    
  # Memory retrieval
  retrieval:
    pattern_matching: true
    contextual_similarity: true
    temporal_consistency: true
    cross_modal_retrieval: true
    
  # Memory compression
  compression:
    enabled: true
    visual_compression: true
    text_compression: true
    compression_ratio: 0.7
    quality_threshold: 0.85

# Performance optimization
performance:
  # OCR processing optimization
  ocr_optimization:
    batch_processing: true
    parallel_ocr: true
    gpu_acceleration: true
    memory_pooling: true
    async_processing: true
    
  # Memory optimization
  memory_optimization:
    lazy_loading: true
    memory_mapping: true
    compression: true
    caching: true
    prefetching: true
    
  # Inference optimization
  inference:
    model_compilation: true
    quantization: true
    pruning: true
    distillation: false
    dynamic_batching: true

# Evaluation metrics
evaluation:
  # OCR accuracy metrics
  ocr_metrics:
    text_reconstruction_accuracy: true
    image_to_text_accuracy: true
    memory_retrieval_accuracy: true
    pattern_recognition_accuracy: true
    
  # Memory efficiency metrics
  memory_metrics:
    memory_compression_ratio: true
    memory_retrieval_speed: true
    memory_storage_efficiency: true
    memory_diversity_score: true
    
  # Performance metrics
  performance_metrics:
    inference_speed: true
    memory_usage: true
    training_convergence: true
    model_size: true

# Debugging and monitoring
debugging:
  # OCR debugging
  ocr_debug:
    save_intermediate_images: false
    log_ocr_accuracy: true
    visualize_memory_images: false
    log_pattern_recognition: true
    
  # Memory debugging
  memory_debug:
    log_memory_operations: true
    track_memory_usage: true
    profile_memory_retrieval: false
    log_memory_statistics: true
    
  # Performance monitoring
  performance_monitoring:
    track_inference_time: true
    monitor_memory_usage: true
    log_training_metrics: true
    profile_ocr_processing: true

# File paths
paths:
  # Model paths
  models:
    tantra_ocr_weights: "Model/tantra_ocr_weights.safetensors"
    tantra_ocr_stages: "Model/tantra_ocr_stage_{stage}.safetensors"
    tokenizer: "Model/tokenizer.json"
    
  # Memory storage
  memory_storage:
    memory_bank: "memory/tantra_ocr_memory_bank"
    memory_images: "memory/images"
    memory_metadata: "memory/metadata.json"
    weight_memories: "memory/weight_memories"
    
  # Training data
  training_data:
    audio_data: "Dataset/audio_data.jsonl"
    text_data: "Dataset/combined_full_training.jsonl"
    vision_data: "Dataset/vision_data.jsonl"
    
  # Outputs
  outputs:
    trained_models: "outputs/tantra_ocr_models"
    evaluation_results: "outputs/evaluation"
    memory_visualizations: "outputs/visualizations"
    ocr_samples: "outputs/ocr_samples"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/tantra_ocr.log"
  
  # OCR-specific logging
  ocr_logging:
    log_ocr_operations: true
    log_memory_operations: true
    log_performance_metrics: true
    log_pattern_recognition: true